package pilotage.metier;


import java.io.Serializable;
import java.math.BigDecimal;

/**
 * BbrConsignes generated by hbm2java
 */
public class Bbr_Consignes  implements Serializable {


     /**
	 * 
	 */
	 private static final long serialVersionUID = 442861859072490951L;

	 
	 private long id;
	 private String bbrorigine;
     private String bbrcomposant;
     private String bbrtype;
     private BigDecimal bbrpriority;
     private String localisation;

    public Bbr_Consignes() {
    }

	
     public Bbr_Consignes(String bbrorigine,String bbrcomposant, String bbrtype, BigDecimal bbrpriority, String localisation) {
        this.bbrorigine = bbrorigine;
        this.bbrcomposant = bbrcomposant;
        this.bbrtype = bbrtype;
        this.bbrpriority = bbrpriority;
        this.localisation = localisation;
     }
    
     public long getId() {
         return this.id;
     }
     public void setId(long id) {
         this.id = id;
     }
    
	/**
	 * Return the value associated with the column: bbrType
	 */
    public String getBbrorigine() {
        return this.bbrorigine;
    }
    
	/**
	 * Set the value related to the column: bbrType
	 * @param bbrType the bbrType value
	 */
    public void setBbrorigine(String bbrorigine) {
        this.bbrorigine = bbrorigine;
    }
	
	/**
	 * Return the value associated with the column: bbrType
	 */
    public String getBbrcomposant() {
        return this.bbrcomposant;
    }
    
	/**
	 * Set the value related to the column: bbrType
	 * @param bbrType the bbrType value
	 */
    public void setBbrcomposant(String bbrcomposant) {
        this.bbrcomposant = bbrcomposant;
    }
	
	/**
	 * Return the value associated with the column: bbrType
	 */
    public String getBbrtype() {
        return this.bbrtype;
    }
    
	/**
	 * Set the value related to the column: bbrType
	 * @param bbrType the bbrType value
	 */
    public void setBbrtype(String bbrtype) {
        this.bbrtype = bbrtype;
    }
	
	/**
	 * Return the value associated with the column: bbrPriority
	 */
    public BigDecimal getBbrpriority() {
        return this.bbrpriority;
    }
    	
	/**
	 * Set the value related to the column: bbrPriority
	 * @param bbrPriority the bbrPriority value
	 */
    public void setBbrpriority(BigDecimal bbrpriority) {
        this.bbrpriority = bbrpriority;
    }
	
	/**
	 * Return the value associated with the column: localisation
	 */
    public String getLocalisation() {
        return this.localisation;
    }
    
	/**
	 * Set the value related to the column: localisation
	 * @param localisation the localisation value
	 */
    public void setLocalisation(String localisation) {
        this.localisation = localisation;
    }
}


