use parametre;
INSERT INTO `droits_liste` (`id`, `libelle`, `description`) VALUES (97, 'ICD_QLT_ADD', 'Droit d\'ajout d\'une fiche incident qualité');
INSERT INTO `droits_liste` (`id`, `libelle`, `description`) VALUES (98, 'ICD_QLT_MOD', 'Droit de modifier une fiche incident qualité');
INSERT INTO `droits_liste` (`id`, `libelle`, `description`) VALUES (99, 'ICD_QLT_DEL', 'Droit de supprimer une fiche incident qualité');
INSERT INTO `droits_liste` (`id`, `libelle`, `description`) VALUES (100, 'ICD_QLT_ACT_ADD', 'Droit d\'ajout d\'une action');
INSERT INTO `droits_liste` (`id`, `libelle`, `description`) VALUES (101, 'ICD_QLT_ACT_MOD', 'Droit de modification d\'une action');
INSERT INTO `droits_liste` (`id`, `libelle`, `description`) VALUES (102, 'ICD_QLT_ACT_DEL', 'Droit de supprimer une action');
INSERT INTO `droits_liste` (`id`, `libelle`, `description`) VALUES (103, 'CSG_BBR_ADD', 'Droit d\'ajout d\'une consigne BBR');
INSERT INTO `droits_liste` (`id`, `libelle`, `description`) VALUES (104, 'CSG_BBR_MOD', 'Droit de modification d\'une consigne BBR');
INSERT INTO `droits_liste` (`id`, `libelle`, `description`) VALUES (105, 'CSG_BBR_DEL', 'Droit de suppression d\'une consigne BBR');
INSERT INTO `droits_liste` (`id`, `libelle`, `description`) VALUES (106, 'APP_ADD', 'Droit d\'ajout d\'une application');
INSERT INTO `droits_liste` (`id`, `libelle`, `description`) VALUES (107, 'APP_MOD', 'Droit de modification d\'une application');
INSERT INTO `droits_liste` (`id`, `libelle`, `description`) VALUES (108, 'APP_DEL', 'Droit de suppression d\'une application');
INSERT INTO `droits_liste` (`id`, `libelle`, `description`) VALUES (109, 'PLN_CYL_ADD', 'Droit d\'ajout d\'un cycle de planning');
INSERT INTO `droits_liste` (`id`, `libelle`, `description`) VALUES (110, 'PLN_CYL_MOD', 'Droit de modification d\'un cycle de planning');
INSERT INTO `droits_liste` (`id`, `libelle`, `description`) VALUES (111, 'PLN_CYL_DEL', 'Droit de suppression d\'un cycle de planning');
INSERT INTO `droits_liste` (`id`, `libelle`, `description`) VALUES (112, 'PLN_EQU_ADD', 'Droit d\'ajout d\'une équipe de planning');
INSERT INTO `droits_liste` (`id`, `libelle`, `description`) VALUES (113, 'PLN_EQU_MOD', 'Droit de modification d\'une équipe de planning');
INSERT INTO `droits_liste` (`id`, `libelle`, `description`) VALUES (114, 'PLN_EQU_DEL', 'Droit de suppression d\'une équipe de planning');
INSERT INTO `droits_liste` (`id`, `libelle`, `description`) VALUES (115, 'PLN_VAC_ADD', 'Droit d\'ajout d\'une vacation de planning');
INSERT INTO `droits_liste` (`id`, `libelle`, `description`) VALUES (116, 'PLN_VAC_MOD', 'Droit de modification d\'une vacation de planning');
INSERT INTO `droits_liste` (`id`, `libelle`, `description`) VALUES (117, 'PLN_VAC_DEL', 'Droit de suppression d\'une vacation de planning');
INSERT INTO `droits_liste` (`id`, `libelle`, `description`) VALUES (118, 'PLN_MOD_PONC', 'Droit de modification ponctuelle du planning d\'un pilote');

INSERT INTO `titre_page` (`ID`, `DESCRIPTION`, `LIBELLE`) VALUES ('ICD_QLT', 'Gestion des FIQ - liste', 'Liste des F.I.Q.');
INSERT INTO `titre_page` (`ID`, `DESCRIPTION`, `LIBELLE`) VALUES ('ICD_QLT_C', 'Gestion des FIQ - création', 'Création d\'une F.I.Q.');
INSERT INTO `titre_page` (`ID`, `DESCRIPTION`, `LIBELLE`) VALUES ('ICD_QLT_M', 'Gestion des FIQ - modification', 'Modification d\'une F.I.Q.');
INSERT INTO `titre_page` (`ID`, `DESCRIPTION`, `LIBELLE`) VALUES ('ICD_Q_A', 'Gestion des FIQ - Actions - liste', 'Liste des actions d\'une F.I.Q.');
INSERT INTO `titre_page` (`ID`, `DESCRIPTION`, `LIBELLE`) VALUES ('ICD_Q_A_C', 'Gestion des FIQ - Actions - création', 'Création d\'une action d\'une F.I.Q.');
INSERT INTO `titre_page` (`ID`, `DESCRIPTION`, `LIBELLE`) VALUES ('ICD_Q_A_M', 'Gestion des FIQ - Actions - modification', 'Modification d\'une action d\'une F.I.Q.');
INSERT INTO `titre_page` (`ID`, `DESCRIPTION`, `LIBELLE`) VALUES ('BBR_ADD', 'Gestion des consignes BBR - création', 'Création d\'une consigne BBR');
INSERT INTO `titre_page` (`ID`, `DESCRIPTION`, `LIBELLE`) VALUES ('BBR_LST', 'Gestion des consignes BBR - liste', 'Liste des consignes BBR');
INSERT INTO `titre_page` (`ID`, `DESCRIPTION`, `LIBELLE`) VALUES ('BBR_MOD', 'Gestion des consignes BBR - modification', 'Modification d\'une consigne BBR');
INSERT INTO `titre_page` (`ID`, `DESCRIPTION`, `LIBELLE`) VALUES ('APP_LST', 'Gestion applications - liste', 'Liste des applications');
INSERT INTO `titre_page` (`ID`, `DESCRIPTION`, `LIBELLE`) VALUES ('APP_MOD', 'Gestion applications - modification', 'Modification d\'une application');
INSERT INTO `titre_page` (`ID`, `DESCRIPTION`, `LIBELLE`) VALUES ('APP_ADD', 'Gestion applications - création', 'Création d\'une application');
INSERT INTO `titre_page` (`ID`, `DESCRIPTION`, `LIBELLE`) VALUES ('PLN_VAC', 'Gestion du planning - Vacation - liste', 'Liste des vacations');
INSERT INTO `titre_page` (`ID`, `DESCRIPTION`, `LIBELLE`) VALUES ('PLN_VAC_C', 'Gestion du planning - Vacation - création', 'Création d\'une vacation');
INSERT INTO `titre_page` (`ID`, `DESCRIPTION`, `LIBELLE`) VALUES ('PLN_VAC_M', 'Gestion du planning - Vacation - modification', 'Modification d\'une vacation');
INSERT INTO `titre_page` (`ID`, `DESCRIPTION`, `LIBELLE`) VALUES ('PLN_CYC_L', 'Gestion des plannings - Cycles - liste', 'Liste des cycles');
INSERT INTO `titre_page` (`ID`, `DESCRIPTION`, `LIBELLE`) VALUES ('PLN_CYC_C', 'Gestion des plannings - Cycles - création', 'Création d\'un cycle de planning');
INSERT INTO `titre_page` (`ID`, `DESCRIPTION`, `LIBELLE`) VALUES ('PLN_CYC_M', 'Gestion des plannings - Cycles - modification', 'Modification d\'un cycle de planning');
INSERT INTO `titre_page` (`ID`, `DESCRIPTION`, `LIBELLE`) VALUES ('PLN_EQU_L', 'Gestion des plannings - Equipes - liste', 'Liste des équipes');
INSERT INTO `titre_page` (`ID`, `DESCRIPTION`, `LIBELLE`) VALUES ('PLN_EQU_C', 'Gestion des plannings - Equipes - création', 'Création d\'une équipe');
INSERT INTO `titre_page` (`ID`, `DESCRIPTION`, `LIBELLE`) VALUES ('PLN_EQU_M', 'Gestion des plannings - Equipes - modification', 'Modification d\'une équipe');
INSERT INTO `titre_page` (`ID`, `DESCRIPTION`, `LIBELLE`) VALUES ('PLN_A', 'Gestion des plannings - Accueil', 'Administration du planning');
INSERT INTO `titre_page` (`ID`, `DESCRIPTION`, `LIBELLE`) VALUES ('PLN_MOIS', 'Gestion des plannings - Mois', 'Administration de planning');
INSERT INTO `titre_page` (`ID`, `DESCRIPTION`, `LIBELLE`) VALUES ('PLN_SEM', 'Gestion des plannings - Semaine', 'Administration de planning');
INSERT INTO `titre_page` (`ID`, `DESCRIPTION`, `LIBELLE`) VALUES ('PLN_MOD', 'Gestion des plannings - Modification ponctuelle', 'Modification ponctuelle de vacation d\'un pilote');
INSERT INTO `titre_page` (`ID`, `DESCRIPTION`, `LIBELLE`) VALUES ('STAT_PRT', 'Statistiques - Incident - impression', 'Choix des modules');


