INSERT INTO `parametre`.`parametre` (`LIBELLE`, `VALEUR`) VALUES 
('TPS_INACTIVITE_SESSION', '43200'),
('BILAN_SERVICE','Exploitation et Datacenter <br/>Pilotage 7/24 Paris');
	
	
DELETE FROM `parametre`.`parametre` WHERE `LIBELLE`='BILAN_ACTIONS_EFFECT';
DELETE FROM `parametre`.`parametre` WHERE `LIBELLE`='BILAN_ALERTE';
DELETE FROM `parametre`.`parametre` WHERE `LIBELLE`='BILAN_ALERTES_FILE';
DELETE FROM `parametre`.`parametre` WHERE `LIBELLE`='BILAN_APPLICATIF';
DELETE FROM `parametre`.`parametre` WHERE `LIBELLE`='BILAN_APP_ASTREINTES';
DELETE FROM `parametre`.`parametre` WHERE `LIBELLE`='BILAN_APREM';
DELETE FROM `parametre`.`parametre` WHERE `LIBELLE`='BILAN_ARS';
DELETE FROM `parametre`.`parametre` WHERE `LIBELLE`='BILAN_ASTREINTES';
DELETE FROM `parametre`.`parametre` WHERE `LIBELLE`='BILAN_DETECTION';
DELETE FROM `parametre`.`parametre` WHERE `LIBELLE`='BILAN_EN_COURS';
DELETE FROM `parametre`.`parametre` WHERE `LIBELLE`='BILAN_ETATS_ESP_DISQUES';
DELETE FROM `parametre`.`parametre` WHERE `LIBELLE`='BILAN_FIN_INC';
DELETE FROM `parametre`.`parametre` WHERE `LIBELLE`='BILAN_FIN_INC_OCEOR';
DELETE FROM `parametre`.`parametre` WHERE `LIBELLE`='BILAN_FLUX_CFT';
DELETE FROM `parametre`.`parametre` WHERE `LIBELLE`='BILAN_FS';
DELETE FROM `parametre`.`parametre` WHERE `LIBELLE`='BILAN_HEURE';
DELETE FROM `parametre`.`parametre` WHERE `LIBELLE`='BILAN_HEURE_OCEOR';
DELETE FROM `parametre`.`parametre` WHERE `LIBELLE`='BILAN_HEURE_PARIS';
DELETE FROM `parametre`.`parametre` WHERE `LIBELLE`='BILAN_INC';
DELETE FROM `parametre`.`parametre` WHERE `LIBELLE`='BILAN_INC_AUTRES';
DELETE FROM `parametre`.`parametre` WHERE `LIBELLE`='BILAN_INC_COUPURE_SERVICE';
DELETE FROM `parametre`.`parametre` WHERE `LIBELLE`='BILAN_INC_CRITIQUES';
DELETE FROM `parametre`.`parametre` WHERE `LIBELLE`='BILAN_INC_DE';
DELETE FROM `parametre`.`parametre` WHERE `LIBELLE`='BILAN_INC_PROD';
DELETE FROM `parametre`.`parametre` WHERE `LIBELLE`='BILAN_INC_RESOLUS';
DELETE FROM `parametre`.`parametre` WHERE `LIBELLE`='BILAN_MATIN';
DELETE FROM `parametre`.`parametre` WHERE `LIBELLE`='BILAN_NB_INC';
DELETE FROM `parametre`.`parametre` WHERE `LIBELLE`='BILAN_NB_INCIDENTS';
DELETE FROM `parametre`.`parametre` WHERE `LIBELLE`='BILAN_NB_MOY_INC';
DELETE FROM `parametre`.`parametre` WHERE `LIBELLE`='BILAN_NON_VERIF';
DELETE FROM `parametre`.`parametre` WHERE `LIBELLE`='BILAN_NUIT';
DELETE FROM `parametre`.`parametre` WHERE `LIBELLE`='BILAN_OBS';
DELETE FROM `parametre`.`parametre` WHERE `LIBELLE`='BILAN_OCCUP_J';
DELETE FROM `parametre`.`parametre` WHERE `LIBELLE`='BILAN_OCCUP_J-1';
DELETE FROM `parametre`.`parametre` WHERE `LIBELLE`='BILAN_PAS_ALERTE_SAISIE';
DELETE FROM `parametre`.`parametre` WHERE `LIBELLE`='BILAN_PAS_ESP_DISQUE';
DELETE FROM `parametre`.`parametre` WHERE `LIBELLE`='BILAN_PAS_INC';
DELETE FROM `parametre`.`parametre` WHERE `LIBELLE`='BILAN_PILOTAGE_OPERAT';
DELETE FROM `parametre`.`parametre` WHERE `LIBELLE`='BILAN_RESP_VACATION';
DELETE FROM `parametre`.`parametre` WHERE `LIBELLE`='BILAN_RESUME_JOUR';
DELETE FROM `parametre`.`parametre` WHERE `LIBELLE`='BILAN_RESUME_MOIS';
DELETE FROM `parametre`.`parametre` WHERE `LIBELLE`='BILAN_SERVEUR';
DELETE FROM `parametre`.`parametre` WHERE `LIBELLE`='BILAN_SEUIL';
DELETE FROM `parametre`.`parametre` WHERE `LIBELLE`='BILAN_SYST';
DELETE FROM `parametre`.`parametre` WHERE `LIBELLE`='BILAN_TITRE';
DELETE FROM `parametre`.`parametre` WHERE `LIBELLE`='BILAN_TYPE';